//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string Documento { get; set; }
        public string NombreCli { get; set; }
        public string NroTarjeta { get; set; }
        public string NroTelefono { get; set; }
        public string Domicilio { get; set; }
    }
}
